version: '3.8'
services:

  pg-nest-launch:
    image: postgres:15.2-alpine
    container_name: pg_nest_launch
    restart: always
    environment: 
      PG_HOST: ${PG_HOST}
      PG_DATABASE: ${PG_DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - pg-nest-launch:/var/lib/postgresql/data

  redis-nest-launch:
    image: redis:latest
    container_name: redis_nest_launch
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-nest-launch:/redis/data

volumes:
  pg-nest-launch:
    driver: local
  redis-nest-launch:
    driver: local
