version: '3.8'
services:

  pg:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/redis/data

volumes:
  pg:
    driver: local
  redis:
    driver: local
